name: diffuser
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip
- patchelf
- pip:
  - -f https://download.pytorch.org/whl/torch_stable.html
  - numpy
  - gym==0.23.1
  - Cython==0.29.36
  - mujoco==2.2.0
  - mujoco-py==2.0.2.10
  - matplotlib
  - seaborn
  - hydra-core
  - omegaconf
  - torch
  - typed-argument-parser
  - git+https://github.com/Farama-Foundation/d4rl@f2a05c0d66722499bf8031b094d9af3aea7c372b#egg=d4rl
  - scikit-image==0.21.0
  - scikit-video==1.1.11
  - gitpython
  - einops
  - ffmpeg
  - ffprobe
  - pillow
  - tqdm
  - pandas
  - wandb
  - flax >= 0.3.5
  - jax <= 0.2.21
  - ray==2.0.0
  - crcmod
  - google-api-python-client
  - cryptography
  - git+https://github.com/JannerM/doodad.git@janner
  - gdown>=4.6.0
  - nvtx